export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const DATA_ROUTE = '/'
export const CHIP_ROUTE = '/chip'
export const ANALIT_ROUTE = '/analit'